---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: windows-2008
    driver_config:
      box: opentable/win-2008r2-standard-amd64-nocm
      network:
        - ["forwarded_port", {guest: 3389, host: 3389}]
suites:
  - name: default
    run_list:
      - recipe[windows_aws_test::default]
    attributes:
