---
driver:
  name: ec2
  aws_ssh_key_id: adufour
  instance_type: t2.medium
  region: us-east-1

transport:
  ssh_key: ~/.ssh/id_rsa

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.13.37
  log_level: debug

platforms:
  - name: windows-2008r2
    #driver:
      #image_id: ami-a2d017cf

suites:
  - name: default
    run_list:
      - recipe[windows_aws_test::default]
    attributes:
